# Generated by Django 5.2.17 on 2026-08-16 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('BRAIN_WAKE', 'Brain Wake'), ('BRAIN_SHIFT', 'Brain Shift'), ('BRAIN_RESET', 'Brain Reset')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('required_landmarks', models.JSONField(blank=True, default=list)),
                ('min_difficulty', models.PositiveSmallIntegerField(default=1)),
                ('max_difficulty', models.PositiveSmallIntegerField(default=5)),
                ('default_duration_sec', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_state', models.ForeignKey(blank=True, help_text='Brain Shift에서만 사용. Wake/Reset은 null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_types', to='common.stateoption')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_no', models.PositiveSmallIntegerField(help_text='1=Wake, 2=Shift, 3=Reset')),
                ('stage_type', models.CharField(choices=[('BRAIN_WAKE', 'Brain Wake'), ('BRAIN_SHIFT', 'Brain Shift'), ('BRAIN_RESET', 'Brain Reset')], max_length=20)),
                ('difficulty_level', models.PositiveSmallIntegerField()),
                ('planned_duration_sec', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('LOCKED', '잠김'), ('AVAILABLE', '진행 가능'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('ABORTED', '중도종료')], default='LOCKED', max_length=20)),
                ('locked_until_previous_done', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_instances', to='routines.activitytype')),
                ('recovery_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_instances', to='plans.recoveryslot')),
            ],
            options={
                'ordering': ['recovery_slot', 'sequence_no'],
                'constraints': [models.UniqueConstraint(fields=('recovery_slot', 'sequence_no'), name='unique_routine_instance_sequence')],
            },
        ),
    ]
