# Generated by Django 5.2.17 on 2026-08-17 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_stateoption_default_difficulty'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='max_difficulty',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='min_difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='target_state',
            field=models.ForeignKey(blank=True, help_text='Brain Shift에서만 사용. Wake/Reset은 null', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_types', to='common.stateoption'),
        ),
        migrations.AlterField(
            model_name='routineinstance',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='routineinstance',
            name='status',
            field=models.CharField(choices=[('LOCKED', '잠김'), ('AVAILABLE', '진행 가능'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('ABORTED', '중도종료'), ('CANCELED', '취소됨')], default='LOCKED', max_length=20),
        ),
    ]
