# Generated by Django 5.2.17 on 2026-08-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_activitytype_max_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineinstance',
            name='stage_type',
        ),
        migrations.AlterField(
            model_name='routineinstance',
            name='status',
            field=models.CharField(choices=[('LOCKED', '잠김'), ('AVAILABLE', '진행 가능'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('CANCELED', '취소됨')], default='LOCKED', max_length=20),
        ),
    ]
