# Generated by Django 5.2.17 on 2026-08-16 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plans', '0001_initial'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, help_text='0~100', null=True)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('ABORTED', '중도종료'), ('RESET', '초기화됨')], default='IN_PROGRESS', max_length=20)),
                ('camera_permission_status', models.CharField(choices=[('UNKNOWN', '확인 전'), ('GRANTED', '허용'), ('DENIED', '거부'), ('PROMPT', '요청중')], default='UNKNOWN', max_length=20)),
                ('reset_count', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='routines.activitytype')),
                ('recovery_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='plans.recoveryslot')),
                ('routine_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='routines.routineinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('step_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sessions_app.session')),
            ],
            options={
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_feeling', models.CharField(blank=True, choices=[('MUCH_BETTER', '훨씬 나아졌어요'), ('SLIGHTLY_BETTER', '조금 나아졌어요'), ('SAME', '비슷해요')], max_length=20, null=True)),
                ('difficulty_feedback', models.CharField(blank=True, choices=[('JUST_RIGHT', '딱 좋았어요'), ('TOO_EASY', '너무 쉬웠어요'), ('A_BIT_HARD', '조금 힘들었어요')], max_length=20, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sessions_app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionMetricSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_no', models.PositiveSmallIntegerField()),
                ('metric_type', models.CharField(max_length=50)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reaction_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_distance_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('raw_payload_json', models.JSONField(blank=True, null=True)),
                ('measured_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='sessions_app.session')),
            ],
            options={
                'ordering': ['session', 'step_no'],
            },
        ),
    ]
