# Generated by Django 5.2.17 on 2026-08-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_recoveryplan_unique_active_plan_per_user_date'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionfeedback',
            name='session',
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='recovery_slot',
            field=models.OneToOneField(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='plans.recoveryslot'),
            preserve_default=False,
        ),
    ]
