# Generated by Django 5.2.17 on 2026-08-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_anonymous'),
        ('plans', '0008_remove_aiplanrun_pc_usage_patterns_and_more'),
        ('routines', '0003_remove_routineinstance_stage_type_and_more'),
        ('sessions_app', '0002_remove_sessionfeedback_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('ABORTED', '중도종료')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('routine_instance',), name='unique_active_session_per_routine_instance'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('user',), name='unique_active_session_per_user'),
        ),
    ]
