# Generated by Django 5.2.17 on 2026-08-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_alter_session_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionMetricSample',
        ),
    ]
