# Generated by Django 5.2.17 on 2026-08-16 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField(db_index=True)),
                ('expected_focus_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('focus_time_option', models.CharField(choices=[('THIRTY_MINUTES', '30분'), ('ONE_HOUR', '1시간'), ('TWO_HOURS', '2시간'), ('CUSTOM', '직접 설정'), ('SKIPPED', '건너뛰기')], max_length=20)),
                ('skipped', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_contexts', to='accounts.user')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyContextActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.activitytag')),
                ('daily_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tag_links', to='context.dailycontext')),
            ],
        ),
        migrations.CreateModel(
            name='DailyContextState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('daily_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_links', to='context.dailycontext')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.stateoption')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddIndex(
            model_name='dailycontext',
            index=models.Index(fields=['user', 'service_date'], name='context_dai_user_id_d054d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycontextactivitytag',
            constraint=models.UniqueConstraint(fields=('daily_context', 'activity_tag'), name='unique_daily_context_activity_tag'),
        ),
        migrations.AddConstraint(
            model_name='dailycontextstate',
            constraint=models.UniqueConstraint(fields=('daily_context', 'state'), name='unique_daily_context_state'),
        ),
    ]
