# Generated by Django 5.2.17 on 2026-08-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_device_code_and_more'),
        ('common', '0002_alter_stateoption_default_difficulty'),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailycontext',
            name='context_dai_user_id_d054d3_idx',
        ),
        migrations.RemoveField(
            model_name='dailycontext',
            name='skipped',
        ),
        migrations.AddField(
            model_name='dailycontext',
            name='state_skipped',
            field=models.BooleanField(default=False, help_text='현재 상태 선택을 건너뛰었는지'),
        ),
        migrations.AddField(
            model_name='dailycontext',
            name='tags_skipped',
            field=models.BooleanField(default=False, help_text='활동 태그 선택을 건너뛰었는지'),
        ),
        migrations.AlterField(
            model_name='dailycontextactivitytag',
            name='activity_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.activitytag'),
        ),
        migrations.AlterField(
            model_name='dailycontextstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.stateoption'),
        ),
        migrations.AddConstraint(
            model_name='dailycontext',
            constraint=models.UniqueConstraint(fields=('user', 'service_date'), name='unique_user_service_date'),
        ),
    ]
