# Generated by Django 5.2.17 on 2026-08-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_remove_dailycontext_context_dai_user_id_d054d3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailycontext',
            name='unique_user_service_date',
        ),
    ]
