# Generated by Django 5.2.17 on 2026-08-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_remove_dailycontext_unique_user_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycontext',
            name='state_skipped',
        ),
    ]
