# Generated by Django 5.2.17 on 2026-08-16 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('TODAY_ANALYSIS', '오늘의 분석'), ('RECOMMENDATION_REASON', '추천 이유'), ('ROUTINE_REASON', '루틴 이유')], max_length=30)),
                ('body', models.TextField()),
                ('data_sources_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPlanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('input_snapshot_json', models.JSONField()),
                ('output_snapshot_json', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('SENT', '발송됨'), ('CLICKED', '클릭됨'), ('FAILED', '실패'), ('CANCELED', '취소됨')], default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-plan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoverySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('recommended_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('user_changed_at', models.DateTimeField(blank=True, null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('repeat_rule', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('RECOMMENDED', '추천됨'), ('SCHEDULED', '예약됨'), ('CHANGED', '변경됨'), ('CANCELED', '취소됨'), ('STARTED', '시작됨'), ('COMPLETED', '완료'), ('MISSED', '놓침')], default='RECOMMENDED', max_length=20)),
            ],
            options={
                'ordering': ['recovery_plan', 'sequence_no'],
            },
        ),
    ]
