# Generated by Django 5.2.17 on 2026-08-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('context', '0001_initial'),
        ('digital_state', '0001_initial'),
        ('plans', '0001_initial'),
        ('routines', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='routine_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='routines.routineinstance'),
        ),
        migrations.AddField(
            model_name='aiplanrun',
            name='daily_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan_runs', to='context.dailycontext'),
        ),
        migrations.AddField(
            model_name='aiplanrun',
            name='digital_data_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_plan_runs', to='digital_state.digitaldataentry'),
        ),
        migrations.AddField(
            model_name='aiplanrun',
            name='reference_sessions',
            field=models.ManyToManyField(blank=True, help_text='이 추천을 생성할 때 참고한 이전 수행 기록(세션)들. 세션 피드백까지 필요하면 별도 필드 추가 필요.', related_name='referenced_in_ai_plan_runs', to='sessions_app.session'),
        ),
        migrations.AddField(
            model_name='aiplanrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan_runs', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='recoveryplan',
            name='ai_plan_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_plans', to='plans.aiplanrun'),
        ),
        migrations.AddField(
            model_name='recoveryplan',
            name='daily_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='context.dailycontext'),
        ),
        migrations.AddField(
            model_name='recoveryplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='recovery_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='plans.recoveryplan'),
        ),
        migrations.AddField(
            model_name='recoveryslot',
            name='recovery_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='plans.recoveryplan'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recovery_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='plans.recoveryslot'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='recovery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='plans.recoveryslot'),
        ),
        migrations.AddConstraint(
            model_name='recoveryslot',
            constraint=models.UniqueConstraint(fields=('recovery_plan', 'sequence_no'), name='unique_slot_sequence'),
        ),
    ]
