# Generated by Django 5.2.17 on 2026-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryplan',
            name='data_source_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recoveryplan',
            name='overall_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recoveryplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('REPLACED', '재설정됨'), ('CANCELED', '취소됨'), ('COMPLETED', '완료')], default='ACTIVE', max_length=20),
        ),
    ]
