# Generated by Django 5.2.17 on 2026-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_state', '0003_remove_digitaldataentry_daily_context_and_more'),
        ('plans', '0003_recoveryplan_data_source_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiplanrun',
            name='digital_data_entry',
        ),
        migrations.AddField(
            model_name='aiplanrun',
            name='pc_usage_patterns',
            field=models.ManyToManyField(blank=True, help_text='비어있으면 오늘의 상황 기반 단건 추천, 있으면 패턴 기반 하루치 일괄 추천', related_name='ai_plan_runs', to='digital_state.pcusagepattern'),
        ),
    ]
