# Generated by Django 5.2.17 on 2026-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_device_code_and_more'),
        ('context', '0002_remove_dailycontext_context_dai_user_id_d054d3_idx_and_more'),
        ('plans', '0004_remove_aiplanrun_digital_data_entry_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recoveryplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'plan_date'), name='unique_active_plan_per_user_date'),
        ),
    ]
