# Generated by Django 5.2.17 on 2026-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_state', '0005_alter_pcusagepattern_options'),
        ('plans', '0005_recoveryplan_unique_active_plan_per_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('TODAY_ANALYSIS', '오늘의 분석'), ('RECOMMENDATION_REASON', '추천 이유'), ('ROUTINE_REASON', '루틴 이유'), ('DATA_INSIGHT', '데이터 인사이트')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aiplanrun',
            name='pc_usage_patterns',
            field=models.ManyToManyField(blank=True, help_text='오늘 요일에 해당하는 패턴이 없으면 오늘의 상황 기반 단건 추천, 있으면 패턴 기반 하루치 일괄 추천', related_name='ai_plan_runs', to='digital_state.pcusagepattern'),
        ),
    ]
