# Generated by Django 5.2.17 on 2026-08-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_aiinsight_insight_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryplan',
            name='data_source_summary',
        ),
        migrations.RemoveField(
            model_name='recoveryplan',
            name='overall_reason',
        ),
    ]
