# Generated by Django 5.2.17 on 2026-08-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_remove_recoveryplan_data_source_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiplanrun',
            name='pc_usage_patterns',
        ),
        migrations.RemoveField(
            model_name='aiplanrun',
            name='reference_sessions',
        ),
        migrations.AlterField(
            model_name='recoveryslot',
            name='status',
            field=models.CharField(choices=[('RECOMMENDED', '추천됨'), ('SCHEDULED', '예약됨'), ('CHANGED', '변경됨'), ('CANCELED', '취소됨'), ('STARTED', '시작됨'), ('COMPLETED', '완료')], default='RECOMMENDED', max_length=20),
        ),
    ]
