# Generated by Django 5.2.17 on 2026-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateOption',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('default_difficulty', models.PositiveSmallIntegerField(default=1)),
                ('routine_direction', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
