# Generated by Django 6.0.5 on 2026-08-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_anonymous'),
        ('common', '0003_seed_brainfit_state_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytag',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='null이면 기본 제공 태그(전체 공개), 값이 있으면 그 사용자만 보이는 직접입력 태그', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_activity_tags', to='accounts.user'),
        ),
    ]
