# Generated by Django 5.2.17 on 2026-08-16 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment_type', models.CharField(choices=[('SMARTPHONE', '스마트폰 중심'), ('PC', 'PC 중심'), ('PC_AND_SMARTPHONE', 'PC + 스마트폰')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_profiles', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('SMARTPHONE', '스마트폰'), ('PC', 'PC')], max_length=20)),
                ('os_type', models.CharField(choices=[('IPHONE', 'iPhone'), ('GALAXY', 'Galaxy'), ('MAC', 'Mac'), ('WINDOWS', 'Windows'), ('OTHER', '기타')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('digital_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='digital_state.digitalprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalDataEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('SCREEN_TIME', 'Screen Time'), ('DIGITAL_WELLBEING', 'Digital Wellbeing'), ('PC_MANUAL', 'PC 수동입력'), ('UNKNOWN', '알 수 없음')], max_length=20)),
                ('input_method', models.CharField(choices=[('IMAGE_UPLOAD', '이미지 업로드'), ('OCR', 'OCR 자동추출'), ('MANUAL', '직접 입력'), ('SKIPPED', '건너뛰기')], max_length=20)),
                ('captured_image_url', models.CharField(blank=True, max_length=500)),
                ('total_usage_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('pc_usage_bucket', models.CharField(blank=True, choices=[('UNDER_2H', '2시간 이하'), ('H2_TO_4H', '2~4시간'), ('H4_TO_6H', '4~6시간'), ('OVER_6H', '6시간 이상')], max_length=20, null=True)),
                ('wake_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', '대기중'), ('EXTRACTED', '추출완료'), ('FAILED', '실패'), ('MANUAL', '수동입력'), ('SKIPPED', '건너뛰기')], max_length=20)),
                ('skipped', models.BooleanField(default=False)),
                ('measured_date', models.DateField(db_index=True)),
                ('daily_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_data_entries', to='context.dailycontext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_data_entries', to='accounts.user')),
                ('digital_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='digital_state.digitalprofile')),
            ],
            options={
                'ordering': ['-measured_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalUsageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('usage_minutes', models.PositiveIntegerField()),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('digital_data_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_items', to='digital_state.digitaldataentry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
