# Generated by Django 5.2.17 on 2026-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_state', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaldataentry',
            name='captured_image_url',
        ),
        migrations.RemoveField(
            model_name='digitaldataentry',
            name='extraction_status',
        ),
        migrations.AlterField(
            model_name='digitaldataentry',
            name='input_method',
            field=models.CharField(choices=[('MANUAL', '직접 입력'), ('SKIPPED', '건너뛰기')], max_length=20),
        ),
        migrations.AlterField(
            model_name='digitaldataentry',
            name='source_type',
            field=models.CharField(choices=[('PC_MANUAL', 'PC 수동입력')], default='PC_MANUAL', max_length=20),
        ),
        migrations.DeleteModel(
            name='DigitalUsageItem',
        ),
    ]
