# Generated by Django 5.2.17 on 2026-08-16 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('digital_state', '0002_remove_digitaldataentry_captured_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaldataentry',
            name='daily_context',
        ),
        migrations.RemoveField(
            model_name='digitaldataentry',
            name='digital_profile',
        ),
        migrations.RemoveField(
            model_name='digitaldataentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='digitaldevice',
            name='digital_profile',
        ),
        migrations.RemoveField(
            model_name='digitalprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='PcUsagePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THU', '목'), ('FRI', '금'), ('SAT', '토'), ('SUN', '일')], max_length=3)),
                ('time_slot', models.CharField(choices=[('MORNING', '오전'), ('LUNCH', '점심'), ('AFTERNOON', '오후'), ('EVENING', '저녁')], max_length=20)),
                ('usage_range', models.CharField(choices=[('UNDER_1H', '1시간 이하'), ('H1_TO_2H', '1~2시간'), ('H2_TO_4H', '2~4시간'), ('H4_TO_6H', '4~6시간'), ('OVER_6H', '6시간 이상')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_usage_patterns', to='accounts.user')),
            ],
            options={
                'ordering': ['user', 'day_of_week', 'time_slot'],
            },
        ),
    ]
