# Generated by Django 5.2.17 on 2026-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_state', '0003_remove_digitaldataentry_daily_context_and_more'),
        ('plans', '0004_remove_aiplanrun_digital_data_entry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalDataEntry',
        ),
        migrations.DeleteModel(
            name='DigitalDevice',
        ),
        migrations.DeleteModel(
            name='DigitalProfile',
        ),
        migrations.AddConstraint(
            model_name='pcusagepattern',
            constraint=models.UniqueConstraint(fields=('user', 'day_of_week', 'time_slot'), name='unique_pattern_per_user_day_slot'),
        ),
    ]
