# Generated by Django 5.2.17 on 2026-08-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_state', '0004_delete_digitaldataentry_delete_digitaldevice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcusagepattern',
            options={},
        ),
    ]
