# Generated by Django 5.2.17 on 2026-08-17 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_anonymous'),
        ('digital_state', '0005_alter_pcusagepattern_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pcusagepattern',
            name='unique_pattern_per_user_day_slot',
        ),
        migrations.RemoveField(
            model_name='pcusagepattern',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='pcusagepattern',
            name='usage_range',
        ),
        migrations.AddField(
            model_name='pcusagepattern',
            name='hour',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcusagepattern',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='pcusagepattern',
            constraint=models.UniqueConstraint(fields=('user', 'day_of_week', 'hour'), name='unique_pattern_per_user_day_hour'),
        ),
    ]
