# Generated by Django 5.2.17 on 2026-08-16 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=64)),
                ('is_anonymous', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('camera_permission_status', models.CharField(choices=[('UNKNOWN', '확인 전'), ('GRANTED', '허용'), ('DENIED', '거부'), ('PROMPT', '요청중')], default='UNKNOWN', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
