# Generated by Django 5.2.17 on 2026-08-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_code',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='camera_permission_status',
        ),
    ]
