"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path
import environ
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, True))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",

    # apps
    "common",
    "accounts",
    "context",
    "digital_state",
    "plans",
    "routines",
    "sessions_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 로그인 없음(익명 사용자, X-Device-Code 헤더 값을 accounts.User.id로 그대로 사용해 구분).
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.DeviceCodeAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",
}

# 로컬 개발(DEBUG=True)에서는 프론트 origin이 자주 바뀌니 전체 허용, 배포 환경에서는
# 실제 프론트 도메인만 명시적으로 허용한다(CORS_ALLOW_ALL_ORIGINS=True로 두면 배포에서도
# 아무 origin이나 다 받아버려서 위험함).
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "https://dgu14thlikelion.shop",
        "https://www.dgu14thlikelion.shop",
        # 프론트 팀원들이 로컬 vite 개발 서버(DEBUG=False인 이 배포 API 대상으로)에서
        # 바로 붙여서 테스트할 수 있게 흔한 vite 기본 포트 몇 개를 미리 허용해둔다.
        "http://localhost:5173",
        "http://localhost:5174",
        "http://localhost:5175",
    ],
)
# django-cors-headers 기본 허용 헤더 목록엔 우리 커스텀 인증 헤더(X-Device-Code)가
# 없어서, CORS_ALLOW_ALL_ORIGINS=False인 배포 환경에서는 preflight가 매번 막힌다
# ("Request header field x-device-code is not allowed"). 기본 목록에 추가만 한다.
CORS_ALLOW_HEADERS = list(default_headers) + ["x-device-code"]

# OpenAI LLM plan generation.
# Team convention uses OPEN_AI_API_KEY; OPENAI_API_KEY is accepted only as a
# fallback for local developer environments.
#
# .env에 키를 붙여넣을 때 메모장/노션 등에서 복사하면 좌우로 스마트따옴표(" ")가
# 같이 딸려오는 실수가 실제로 있었다 — 그 상태로 Authorization 헤더를 만들면
# latin-1 인코딩 에러(UnicodeEncodeError)로 요청 자체가 500으로 죽는다. 여기서
# 미리 벗겨내서, 다음에 또 같은 실수를 해도 서버가 안 죽고 그냥 "키가 유효하지
# 않다"는 OpenAI 쪽 401만 나게 만든다.
_QUOTE_CHARS = "\"'“”‘’`"


def _strip_wrapping_quotes(value):
    return value.strip().strip(_QUOTE_CHARS).strip()


OPENAI_API_KEY = _strip_wrapping_quotes(env("OPEN_AI_API_KEY", default=env("OPENAI_API_KEY", default="")))
OPENAI_MODEL = env("OPEN_AI_MODEL", default="gpt-5")
OPENAI_BASE_URL = env("OPENAI_BASE_URL", default="https://api.openai.com/v1")
OPENAI_TIMEOUT_SECONDS = env.int("OPENAI_TIMEOUT_SECONDS", default=30)

# Web Push. The public key is sent to browsers for PushManager.subscribe();
# the private key stays server-side and is used by the notification worker.
WEB_PUSH_VAPID_PUBLIC_KEY = env("WEB_PUSH_VAPID_PUBLIC_KEY", default="")
WEB_PUSH_VAPID_PRIVATE_KEY = env("WEB_PUSH_VAPID_PRIVATE_KEY", default="")
WEB_PUSH_VAPID_SUBJECT = env("WEB_PUSH_VAPID_SUBJECT", default="mailto:admin@example.com")
WEB_PUSH_TTL_SECONDS = env.int("WEB_PUSH_TTL_SECONDS", default=3600)
WEB_PUSH_TIMEOUT_SECONDS = env.int("WEB_PUSH_TIMEOUT_SECONDS", default=10)

# 시연/테스트 전용 데모 모드 (기본값 False로 안전 세팅 -> AI 1차 채점 시 20분/30분 학술 지침 정상 작동)
# 현장 시연 시 서버 환경변수 DEMO_MODE=true 로 켜면 10초/15초 시연 모드 작동
DEMO_MODE = env.bool("DEMO_MODE", default=False)


